name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get



      - name: Build Windows
        run: flutter build windows

      - name: Create MSIX Package
        run: dart run msix:create

      - name: Create Installer
        run: iscc windows\installer.iss

      - name: Upload Installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: TextMerger_Installer
          path: build\windows\installer\TextMerger_Installer.exe

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: TextMerger_MSIX
          path: build\windows\x64\runner\Release\*.msix
